### ISSUE TITLE
Runtime scripting

### ISSUE THREAD

**Issue by Frontrider** [gilzoide/godot-lua-pluginscript#26]
Can I use it at runtime to execute lua scripts? (without compromising the rest of the application)

**Comment by gilzoide** [comment]
My understanding of your question is that it's about executing Lua scripts that are generated at runtime, for example written by users. I'll answer based on that assumption, please let me know if it's not about that.

So the short answer is yes, absolutely! If you want to execute arbitrary scripts and don't want to create your own scripting language/runtime, Lua is the first tool that comes to mind.

If using Lua PluginScript, you have a full LuaJIT runtime embedded in Godot, so you can use the customary functions `load` and `loadfile` to execute arbitrary code.

If you look up the keywords "Lua" and "sandbox", you'll find a lot of content on how to protect code execution from accessing unsafe stuff. It's hard to do it 100%, but depending on your needs, it may be easy enough to make a decent sandbox that won't break the game's code. Maybe it will be vulnerable to inifinite loops and freeze the app in the user's machine or allocate too much memory and crash, these are some hard ones to sandbox. But if it can't mess with the game code/functions/variables, might be good enough.

**Comment by Frontrider** [comment]
Yap, that is exactly what I wanted to know. Thank you.

**Comment by Frontrider** [comment]
I could suggest spelling this out in the first paragraph, so it becomes 1000% obvious.
