### ISSUE TITLE
Mono: Core API Hash Mismatch Error.

### ISSUE THREAD

**Issue by Ayush4441** [gilzoide/godot-lua-pluginscript#53]
In Godot 3.5.x Mono, this error occurs when a C# solution has been built before running.

Error Message:
E 0:00:00.560   _init_godot_api_hashes: Mono: Core API hash mismatch.
  <C++ Source>  modules/mono/mono_gd/gd_mono.cpp:515 @ _init_godot_api_hashes()

**Comment by gilzoide** [comment]
I don't think a "Core API hash mismatch" in GDMono error would be related to Lua PluginScript.
Does this error occur only when the plugin is not installed? Maybe try removing the plugin and seeing if the error persists.

**Comment by Ayush4441** [comment]
The "Core API hash mismatch" error occurs only when I run Godot with the Lua PluginScript installed alongside the C# solution I've created. When I remove the plugin, the error does not occur.

**Comment by Ayush4441** [comment]
Thank you for checking into this. If this error doesn't affect my project in any way, I won't worry about it.

I appreciate your investigation.
