### ISSUE TITLE
get_overlapping_areas() Gets all Areas Regardless of Mask.

### ISSUE THREAD

**Issue by Jamtoad** [gilzoide/godot-lua-pluginscript#8]
Hi, me again! I also noticed that the `Area2D:get_overlapping_areas()` appears to get all overlapping areas regardless of mask.

I have the player on Layer 1, and masked to see layer 6. I also have an object on Layer 7.

It is picking up the object on layer 7, even know I do not have it checked. I have tested the same code in GDScript and it appears to get only the objects on layer 6. Whilst the Lua code gets objects on all layers.

Any ideas?

Thank you and have a good one!

**Comment by gilzoide** [comment]
Hello again!

Hmm, that's weird... The functionality should be the same regardless of scripting language, so my first guess is that you setup the objects and/or scene differently in your tests.

One test that you could do is write the exact same logic in Lua and GDScript and run each of them in the same object in your problematic scene. I really mean the same object. Try with one script first, see the error, then change the script in the same object to the other implementation and run again. I don't know if that's what you did already, but this is a way to isolate the scripts from other factors that could be causing the problem.

I won't discard that something in the plugin could be wrong, of course. Anything different is a potential cause for different behaviors. Programming, right? =P
Without a reproduction project to debug this, it's difficult to think of more possibilities.
Do you have/could you make a minimal project with a scene setup with the bug happening, that I could run and reproduce the problem?

**Comment by Jamtoad** [comment]
I did some more testing.

Object is on Layer 7 looking for Mask 1.
Player is on Layer 1 Looking for Mask 6.

Does get_overlapping_areas() return objects that are looking for its layer as well? Like in the example above ^. I thought get_overlapping_areas() only returned objects in the mask you specified, but it appears after some testing that it is returning the mask as well as all objects that are looking for that layer. So in the example above its printing the objects even know they arent in the mask the player is looking for, purely because objects is looking for mask 1. Which is the layer that the player is on.

**Comment by gilzoide** [comment]
By the [docs](https://docs.godotengine.org/en/stable/tutorials/physics/physics_introduction.html#code-example) physics layers are bit masks.
Maybe you changed stuff by code using the number 7, which would be 0b111, which in turn are layers 3, 2 and 1?

> Sorry for posting it here

Don't worry ^^
